### ISSUE TITLE
Size command while game in play

### ISSUE THREAD

**Issue by Allybag** [nelhage/taktician#23]
subhog was playing a 6s game against Taktician, when Conquest requested Taktician to switch to size 4 (Conquest: TakticianBot: size 4)

TakticianBot then disconnected and reconnected a number of times from subhog's game, before playing a terrible move (18 f2??) which immediately allowed an otherwise very blockable road.

https://www.playtak.com/games/416997/playtakviewer

**Comment by nelhage** [comment]
#24 should fix the immediate problem, which is that we sent a Seek in the middle of a game, the server gave us an error, and we disconnected.

There's another hairy problem here where, on reconnect, we immediately send a `Seek`, but if a game is in-progress the server also tries to continue the game, and so our Seek gets an error and we crashloop; that's what happened after the reconnect. That one will be a bit more fiddly to fix.

**Comment by Allybag** [comment]
Quick turnaround!

Cheers.
