### ISSUE TITLE
Friendly Bot Level in PTN

### ISSUE THREAD

**Issue by nqeron** [nelhage/taktician#5]
For games against Friendly Bot, can you have it put the level played against in the PTN?

e.g.

[Site "PlayTak.com"]
[Event "Online Play"]
[Date "2016.06.24"]
[Player1 "X"]
[Player2 "FriendlyBot - level 6"]
[Result "R-0"]
[Size "6"]

(If the level is changed, maybe notate the move # and the level changed to?)

**Comment by nelhage** [comment]
For which PTNs? I don't think we have the ability to alter the information or comments that appear in server-generated PTNs, and the bots don't currently produce any of their own ptn files.

**Comment by nqeron** [comment]
Hmm... that's a good point. Maybe I should make the request to the server side to see if we can add bot meta-data to the ptn. (Then we can re-open this)
