### ISSUE TITLE
parse error: bad move

### ISSUE THREAD

**Issue by NoHatCoder** [nelhage/taktician#6]
The command line interface for playing seems to be broken, no matter what I type I get a parse error.

**Comment by nelhage** [comment]
I assume you mean `playtak`? it works for me locally if I enter ptn notation; What platform are you  running it on? I wonder if there's a newline issue or something.

**Comment by NoHatCoder** [comment]
Windows 7 64 bit, 64 bit compilation. Run it with "go run main.go". Looking at your latest fix, maybe there is a \r left in the string?

**Comment by NoHatCoder** [comment]
Yep, adding in "line = strings.TrimRight(line, "\r")" seems to have fixed it. Thanks for the help.

**Comment by nelhage** [comment]
Thanks for the report! Let me know if that patch doesn't fix it for any reason.
