### ISSUE TITLE
different values for WinReason (Python)

### ISSUE THREAD

**Issue by nqeron** [nelhage/taktician#8]
In the python game.py I noticed that you had 
`class WinReason(enum.Enum):
  ROAD = 1
  FLATS = 1`

This would mean that WinReason.ROAD == WinReason.FLATS. Should the two win reasons instead have different values?

**Comment by nelhage** [comment]
Thanks! Good catch. Out of curiosity, are you using the code for something, or just curious?

**Comment by nqeron** [comment]
Mostly just curious. I was trying to figure out how you solved the "are there any roads on the board" problem.
